name: Rebuild Index
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Restore cache
      id: cache-ql
      uses: actions/cache@v3
      with:
        path: |
          ~/quicklisp/
          ~/.cache/common-lisp/
          ~/.sbclrc
        key: ql
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        ref: 'web'
        path: 'web/'
    - name: Install sbcl
      run: |
        sudo apt-get -qq update | true
        sudo apt-get -qq install sbcl curl
    - name: Install Quicklisp
      run: |
        curl -o ~/quicklisp.lisp https://beta.quicklisp.org/quicklisp.lisp
        sbcl --load ~/quicklisp.lisp --eval '(quicklisp-quickstart:install)' --eval '(ql-util:without-prompting (ql:add-to-init-file))' --quit
    - name: Rebuild the index
      run: |
        ./compile.lisp
    - name: GH Pages deploy
      if: github.head_ref == null
      run: |
        git config --global user.name "CI"
        git config --global user.email "shinmera@tymoon.eu"
        cp *.html *.sexpr *.mess $GITHUB_WORKSPACE/web/
        cd $GITHUB_WORKSPACE/web/
        git add .
        git commit -qm "CI index rebuild." || echo "Nothing to commit."
        git push -q origin web
